# Development env to run Next.
# It runs a PostgreSQL, identical how it works in production

services:
  db:
    image: postgres:16-alpine
    container_name: postgresql-ongoings-countdown
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: ongoings-countdown-database
    ports:
      - "5432:5432" # Exposes DB to your host machine
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: