import type { Metadata } from "next"
import { Toaster } from "@/components/ui/sonner"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Header from "@/components/idk/Header/components/Header"
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { SelectedDayProvider } from "@/providers/SelectedDayContext"
import { Suspense } from "react"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full max-w-480 mx-auto flex flex-col font-[Geist]">
        <Suspense>
          <SelectedDayProvider>
            <Header />
            <NuqsAdapter>
              {children}
            </NuqsAdapter>
          </SelectedDayProvider>
        </Suspense>

        <Toaster richColors />
      </body>
      
    </html>
  )
}


